### ISSUE TITLE
lobby options

### ISSUE THREAD

**Issue by ItsNotPaths** [Bolt-Collective/Prop-Hunt-Issues#11]
create a lobby options system with the following  options (more may be added)

- [x] ~~password~~ (not feasably possible until facepunch changes adds smth)
- [ ] hunter glow through walls from the prop POV
- [x] forced taunt cooldown time
- [x] manual taunt cooldown time
- [x] round time
- [x] player limit
- [x] hunter enable, disable or bleed upon picking up physics props

**Comment by Nolankicks** [comment]
@trende2001 I think we should both work on this. I can work on the code part of it. But can you do the ui?
