### ISSUE TITLE
fix uncrouch ray check misaliognment

### ISSUE THREAD

**Issue by ItsNotPaths** [Bolt-Collective/Prop-Hunt-Issues#16]
when uncrouching the check for uncrouching is taller then your actual uncrouched hitbox, preventing you from uncrouching in areas you should be able to uncrouch under

**Comment by Nolankicks** [comment]
I don't think this is the case. The trace is actually shorter than the height of the CharacterController. I'll have to do some tests. But I think it is visual.

**Comment by ItsNotPaths** [comment]
i just tested it again and its fixed now?
