### ISSUE TITLE
map queue for host and suggetions for non hosts

### ISSUE THREAD

**Issue by ItsNotPaths** [Bolt-Collective/Prop-Hunt-Issues#27]
allow the host to queue up maps that are switched to once the round ends
allow non hosts to queue maps to a "requested" list on the hosts map queue addition UI
likely from the pause menu

**Comment by Nolankicks** [comment]
We already have a system in place to change maps. Should be easy enough to implement. I’ll work on it when I get back from my trip.

**Comment by trende2001** [comment]
you mean rock the vote? like in gmod ttt for example
