### ISSUE TITLE
scene / game kill boundary based on map size

### ISSUE THREAD

**Issue by ItsNotPaths** [Bolt-Collective/Prop-Hunt-Issues#5]
we have 2 ways of tackling this, one slightly better in practise and harder to impliment and the other easier to impliment but likely worse in general usecases

a) just get map bounds and make a kill boundary based on that (includes skybox objects that may inflate or make the killbox boundary inept)

b) get positions of all physics props, create a killbox based on the span between -x and +x (and Y) positions as well as adding a buffer. this makes the killboundary specifically around only the playable space and completely ignores skybox objects

**Comment by Nolankicks** [comment]
I don't really see a need for this. We shouldn't just be duck taping issues by just killing players outside the bounds. What we should be doing is fixing the issues that is the cause wanting of the kill barrier.

**Comment by ItsNotPaths** [comment]
its more of a failsafe in the case of players picking broken maps / getting softlocked / not needing to use kill in the console
