### ISSUE TITLE
BUG - Player props can turn into citzens

### ISSUE THREAD

**Issue by ItsNotPaths** [Bolt-Collective/Prop-Hunt-Issues#6]
we can solve this 2 ways

a) replace the broken citzen model the prop player turns into with a mannequin like game model
b) remove this entirely
c) replace the broken citzen model with an exact recreation of the hunter they turned into, becoming a doppleganger of sorts

though funny, its very buggy and unpolished and may be confusing to new players as it has no practical use

**Comment by Nolankicks** [comment]
This has been fixed
